package com.example.finalyearproject.ui;

import android.content.ContentResolver;
import android.content.Intent;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.provider.OpenableColumns;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.Button;
import android.widget.ProgressBar;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.result.ActivityResultLauncher;
import androidx.activity.result.contract.ActivityResultContracts;
import androidx.annotation.Nullable;
import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.RecyclerView;

import com.example.finalyearproject.R;

public class HomePGActivity extends AppCompatActivity {

    private TextView selectedFileTV;
    private Button pickFileBtn, uploadBtn;
    private ProgressBar uploadProgress;
    private RecyclerView previousFilesRV;

    //parameters for the dile selected by user
    private Uri selectedFileUri = null;
    private String selectedFileName;

    private ActivityResultLauncher<Intent> pickFileLauncher;

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState){
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_homepg);

        selectedFileTV = findViewById(R.id.selectedFileTV);
        pickFileBtn = findViewById(R.id.pickFileBtn);
        uploadBtn = findViewById(R.id.uploadBtn);
        uploadProgress = findViewById(R.id.uploadProgress);
        previousFilesRV = findViewById(R.id.previousFilesRV);
        Toolbar toolbar = findViewById(R.id.homeToolbar);
        setSupportActionBar(toolbar);


        setupFilePicker();

        pickFileBtn.setOnClickListener(v -> openFilePicker());
        uploadBtn.setOnClickListener(v -> onUploadClicked());
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu){
        getMenuInflater().inflate(R.menu.menu_homepg, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item){
        int id = item.getItemId();
        if (id == R.id.action_my_files) {
            // create a my uploads screen
            Toast.makeText(this, "My Uploads", Toast.LENGTH_SHORT).show();
            return true;
        } else if (id == R.id.action_settings) {
            // create a settings page
            Toast.makeText(this, "Settings", Toast.LENGTH_SHORT).show();
            return true;
        } else if (id == R.id.action_logout) {
            Intent intent = new Intent(HomePGActivity.this, MainActivity.class);
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TASK);
            startActivity(intent);
            finish();
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    //how we receive picked file
    private void setupFilePicker() {
        pickFileLauncher = registerForActivityResult(
                new ActivityResultContracts.StartActivityForResult(),
                result -> {
                    if (result.getResultCode() == RESULT_OK && result.getData() != null){
                        Uri uri = result.getData().getData();
                        if (uri != null){
                            selectedFileUri = uri;
                            selectedFileName = getFileNameFromUri(uri);
                            selectedFileTV.setText("Selected: " + selectedFileName);
                        }
                    }
                }
        );
    }

    //launch system file picker
    private void openFilePicker(){
        Intent intent = new Intent(Intent.ACTION_OPEN_DOCUMENT);
        intent.addCategory(Intent.CATEGORY_OPENABLE);

        //allowing multiple file types to be uploaded
        intent.setType("*/*");
        String[] mimeTypes = new String[]{
                "application/pdf",
                "application/msword",
                "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                "application/vnd.ms-powerpoint",
                "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                "text/plain"
        };

        intent.putExtra(Intent.EXTRA_MIME_TYPES, mimeTypes);
        pickFileLauncher.launch(intent);
    }

    //method to start upload of file and generate audio
    private void onUploadClicked() {
        if(selectedFileUri == null){
            toast("Please choose a file first.");
            return;
        }

        //need to send off the selected file to backend using retrofit
        //get back audio file that was generated by the appp
    }

    private String getFileNameFromUri(Uri uri){
        String result = null;
        ContentResolver cr = getContentResolver();
        Cursor cursor = cr.query(uri, null, null, null, null);
        try{
            if(cursor != null && cursor.moveToFirst()){
                int nameIndex = cursor.getColumnIndexOrThrow(OpenableColumns.DISPLAY_NAME);
                if (nameIndex >= 0){
                    result = cursor.getString(nameIndex);
                }
            }
        }finally {
            if(cursor != null){
                cursor.close();
            }
        }
        if (result == null){
            result = uri.getLastPathSegment();
        }

        return result != null ? result : "Unnamed File";
    }



    private void toast(String msg){
        Toast.makeText(this, msg, Toast.LENGTH_SHORT).show();
    }
}
